Issue #515: Add ColumnStats Schema for JSON parsing
Qbeast-io/qbeast-spark pull request #522
Opened 2024-12-16 10:24 UTC by osopardo1

## Description

Fixes #515 . 

In this PR, we are adding a way of building a `columnStats` Schema using the current column `Transformers` and the actual `Schema` of the Data. We want to:
- Ensure the fields are properly parsed from the JSON string. 
- If a JSON string is specified, but the row is returned null, we assume the string is not following the correct syntax.

For that, I've added a `QbeastColumnStats` case class that contains the `columnStatsSchema` and the `columnStatsRow`. Also, a `QbeastColumnStatsBuilder` is needed to retrieve all the information given the parameters mentioned above. 

```scala

case class QbeastColumnStats(columnStatsSchema: StructType, columnStatsRow: Row)

object QbeastColumnStatsBuilder {
  /**
   * Builds the QbeastColumnStats
   *
   * @param statsString
   *   the stats in a JSON string
   * @param columnTransformers
   *   the set of columnTransformers to build the Stats from
   * @param dataSchema
   *   the data schema to build the Stats from
   * @return
   */
  def build(
      statsString: String,
      columnTransformers: Seq[Transformer],
      dataSchema: StructType): QbeastColumnStats
}
```

## Type of change

Bug fix.

## Checklist:

Here is the list of things you should do before submitting this pull request:

- [x] New feature / bug fix has been committed following the [Contribution guide](https://github.com/Qbeast-io/qbeast-spark/blob/main/CONTRIBUTING.md).
- [x] Add logging to the code following the [Contribution guide](https://github.com/Qbeast-io/qbeast-spark/blob/main/CONTRIBUTING.md).
- [x] Add comments to the code (make it easier for the community!).
- [x] Change the documentation.
- [x] Add tests.
- [x] Your branch is updated to the main branch (dependent changes have been merged).

## How Has This Been Tested? (Optional)

Testing different parsings on `QbeastColumnStatsTestBuilder`.

2025-01-09 13:24 UTC, Jiaweihu08 requested changes

2025-01-09 13:24 UTC, Jiaweihu08 commented on core/src/main/scala/io/qbeast/core/model/QbeastColumnStats.scala
> +   * For each column transformer, it creates a StructField with it's stats names
"it creates a StructField with the stats names"

2025-01-09 13:24 UTC, Jiaweihu08 commented on core/src/main/scala/io/qbeast/core/model/QbeastColumnStats.scala
> +object QbeastColumnStatsBuilder {
The builder design pattern follows the syntax of:
```scala
builder
.setAttr1(someAttr1)
.setAttr2(someAttr2)
.setAttr3(someAttr3)
.result()
```
Which isn't the case here.

I'd recommend using an `apply` method with a companion object for `QbeastColumnStats,` which returns `Option[QbeastColumnStats].` The output should be `None` when the requirements are not met.

2025-01-09 13:24 UTC, Jiaweihu08 commented on core/src/main/scala/io/qbeast/spark/index/SparkRevisionFactory.scala
> +      try {
This logic here can be placed in a method in `QbeastColumnStats.`
In this way, the logic will be more clear:
1. We create an object of QbeastColumnStats
2. Then we use this object to create `Transformations.` If the columns are absent in the stats, we log a warning and return `None.`

2025-01-09 13:24 UTC, Jiaweihu08 commented on src/test/scala/io/qbeast/spark/index/SparkRevisionChangesUtilsTest.scala
> +  it should "createNewRevision with column stats for all numeric types" in withSpark(spark => {
There's a list of tests at the beginning of this file. It was made for clarity and to organize the tests, as there are too many cases to cover. 

Please add this test to the list and place it in its proper place, i.e., somewhere in the section of _**// Transformation changes (with columnStats)**_

2025-01-09 13:24 UTC, Jiaweihu08 commented on core/src/main/scala/io/qbeast/spark/index/SparkRevisionFactory.scala
> +      try {
With that, we can also reduce the number of exceptions thrown here.

2025-01-10 08:38 UTC, osopardo1 commented on core/src/main/scala/io/qbeast/core/model/QbeastColumnStats.scala
> +          transformerStatsNames.map(statName =>
it makes me doubt, but... I think is correct since it is a single stat name, no?

2025-01-16 09:21 UTC, Jiaweihu08 approved these changes

2025-01-16 09:26 UTC, merged